### ISSUE TITLE
Wrong sed usage

### ISSUE THREAD

**Issue by zhengliw** [TheGuywithTheHat/noip-ipv6-duc#2]
I'm not familiar with bash, but I noticed that the sed line has to be completed.

The original sed line:

`addr=$(ip -6 addr show dev $interface | sed -e'/inet6/,/scope global/s/^.*inet6 \([^ ]*\)\/.*scope global.*$/\1/;t;d')`

My change:

`addr=$(ip -6 addr show dev $interface | sed -e'/inet6/,/scope global/s/^.*inet6 \([^ ]*\)\/.*scope global temporary.*$/\1/;t;d')`

The prior one returns all ipv6 addresses and results in wrong updating.

**Comment by TheGuywithTheHat** [comment]
Automatically figuring out which ip to use is difficult, and varies from machine to machine. What you changed presumably fixes it for you, but is likely to break it for most other people.
