### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [TheGuywithTheHat/noip-ipv6-duc#4]

**Comment by TheGuywithTheHat** [comment]
This would require solving or circumventing a captcha, neither of which are things I am willing to do.

**Comment by bphd** [comment]
You can take an existing captcha resolver

**Comment by TheGuywithTheHat** [comment]
You can do that in your own repository if you want to. Personally, I do not wish to directly associate with things that I view as unethical. The entire point of the captcha is to require human input. If I'm actively making use of my subdomain, it's a small price to pay: _literally_ 10 seconds a month to click the link in the email, click the captcha, and then confirm the renewal.
